// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Inicializacao_screen_init(void)
{
    ui_Inicializacao = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Inicializacao, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Inicializacao, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Inicializacao, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Olho_Esq = lv_obj_create(ui_Inicializacao);
    lv_obj_remove_style_all(ui_Olho_Esq);
    lv_obj_set_width(ui_Olho_Esq, 50);
    lv_obj_set_height(ui_Olho_Esq, 50);
    lv_obj_set_align(ui_Olho_Esq, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Olho_Esq, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Olho_Esq, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Olho_Esq, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Olho_Esq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Olho_Dir = lv_obj_create(ui_Inicializacao);
    lv_obj_remove_style_all(ui_Olho_Dir);
    lv_obj_set_width(ui_Olho_Dir, 50);
    lv_obj_set_height(ui_Olho_Dir, 50);
    lv_obj_set_align(ui_Olho_Dir, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Olho_Dir, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Olho_Dir, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Olho_Dir, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Olho_Dir, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Boca = lv_obj_create(ui_Inicializacao);
    lv_obj_remove_style_all(ui_Boca);
    lv_obj_set_width(ui_Boca, 10);
    lv_obj_set_height(ui_Boca, 10);
    lv_obj_set_align(ui_Boca, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Boca, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Boca, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Boca, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



}
