// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_OlhandoDir_screen_init(void)
{
    ui_OlhandoDir = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_OlhandoDir, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OlhandoDir, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OlhandoDir, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Olho_Esq2 = lv_obj_create(ui_OlhandoDir);
    lv_obj_remove_style_all(ui_Olho_Esq2);
    lv_obj_set_width(ui_Olho_Esq2, 50);
    lv_obj_set_height(ui_Olho_Esq2, 50);
    lv_obj_set_x(ui_Olho_Esq2, 0);
    lv_obj_set_y(ui_Olho_Esq2, 90);
    lv_obj_set_align(ui_Olho_Esq2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Olho_Esq2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Olho_Esq2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Olho_Esq2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Olho_Esq2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Olho_Dir2 = lv_obj_create(ui_OlhandoDir);
    lv_obj_remove_style_all(ui_Olho_Dir2);
    lv_obj_set_width(ui_Olho_Dir2, 50);
    lv_obj_set_height(ui_Olho_Dir2, 50);
    lv_obj_set_x(ui_Olho_Dir2, 0);
    lv_obj_set_y(ui_Olho_Dir2, -90);
    lv_obj_set_align(ui_Olho_Dir2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Olho_Dir2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Olho_Dir2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Olho_Dir2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Olho_Dir2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Boca2 = lv_obj_create(ui_OlhandoDir);
    lv_obj_remove_style_all(ui_Boca2);
    lv_obj_set_width(ui_Boca2, 10);
    lv_obj_set_height(ui_Boca2, 150);
    lv_obj_set_align(ui_Boca2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Boca2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Boca2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Boca2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_OlhandoDir, ui_event_OlhandoDir, LV_EVENT_ALL, NULL);

}
