// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Piscando_screen_init(void)
{
    ui_Piscando = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Piscando, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Piscando, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Piscando, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Olho_Esq1 = lv_obj_create(ui_Piscando);
    lv_obj_remove_style_all(ui_Olho_Esq1);
    lv_obj_set_width(ui_Olho_Esq1, 50);
    lv_obj_set_height(ui_Olho_Esq1, 50);
    lv_obj_set_x(ui_Olho_Esq1, 0);
    lv_obj_set_y(ui_Olho_Esq1, 90);
    lv_obj_set_align(ui_Olho_Esq1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Olho_Esq1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Olho_Esq1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Olho_Esq1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Olho_Esq1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Olho_Dir1 = lv_obj_create(ui_Piscando);
    lv_obj_remove_style_all(ui_Olho_Dir1);
    lv_obj_set_width(ui_Olho_Dir1, 50);
    lv_obj_set_height(ui_Olho_Dir1, 50);
    lv_obj_set_x(ui_Olho_Dir1, 0);
    lv_obj_set_y(ui_Olho_Dir1, -90);
    lv_obj_set_align(ui_Olho_Dir1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Olho_Dir1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Olho_Dir1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Olho_Dir1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Olho_Dir1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Boca1 = lv_obj_create(ui_Piscando);
    lv_obj_remove_style_all(ui_Boca1);
    lv_obj_set_width(ui_Boca1, 10);
    lv_obj_set_height(ui_Boca1, 150);
    lv_obj_set_align(ui_Boca1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Boca1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Boca1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Boca1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Piscando, ui_event_Piscando, LV_EVENT_ALL, NULL);

}
