// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void OlhoEsq_Animation(lv_obj_t * TargetObject, int delay);
void OlhoDir_Animation(lv_obj_t * TargetObject, int delay);
void Boca_Animation(lv_obj_t * TargetObject, int delay);
void OlhoFocando_Animation(lv_obj_t * TargetObject, int delay);
void OlhandoEsquerda_Animation(lv_obj_t * TargetObject, int delay);
void OlhandoDireita_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Inicializacao
void ui_Inicializacao_screen_init(void);
extern lv_obj_t * ui_Inicializacao;
extern lv_obj_t * ui_Olho_Esq;
extern lv_obj_t * ui_Olho_Dir;
extern lv_obj_t * ui_Boca;
// CUSTOM VARIABLES

// SCREEN: ui_Piscando
void ui_Piscando_screen_init(void);
void ui_event_Piscando(lv_event_t * e);
extern lv_obj_t * ui_Piscando;
extern lv_obj_t * ui_Olho_Esq1;
extern lv_obj_t * ui_Olho_Dir1;
extern lv_obj_t * ui_Boca1;
// CUSTOM VARIABLES

// SCREEN: ui_OlhandoDir
void ui_OlhandoDir_screen_init(void);
void ui_event_OlhandoDir(lv_event_t * e);
extern lv_obj_t * ui_OlhandoDir;
extern lv_obj_t * ui_Olho_Esq2;
extern lv_obj_t * ui_Olho_Dir2;
extern lv_obj_t * ui_Boca2;
// CUSTOM VARIABLES

// SCREEN: ui_OlhandoEsq
void ui_OlhandoEsq_screen_init(void);
void ui_event_OlhandoEsq(lv_event_t * e);
extern lv_obj_t * ui_OlhandoEsq;
extern lv_obj_t * ui_Olho_Esq3;
extern lv_obj_t * ui_Olho_Dir3;
extern lv_obj_t * ui_Boca3;
// CUSTOM VARIABLES

// SCREEN: ui_Simples
void ui_Simples_screen_init(void);
extern lv_obj_t * ui_Simples;
extern lv_obj_t * ui_Olho_Esq4;
extern lv_obj_t * ui_Olho_Dir4;
extern lv_obj_t * ui_Boca4;
// CUSTOM VARIABLES

// EVENTS

void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
