// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_OlhandoEsq_screen_init(void)
{
    ui_OlhandoEsq = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_OlhandoEsq, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OlhandoEsq, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OlhandoEsq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Olho_Esq3 = lv_obj_create(ui_OlhandoEsq);
    lv_obj_remove_style_all(ui_Olho_Esq3);
    lv_obj_set_width(ui_Olho_Esq3, 50);
    lv_obj_set_height(ui_Olho_Esq3, 50);
    lv_obj_set_x(ui_Olho_Esq3, 0);
    lv_obj_set_y(ui_Olho_Esq3, 90);
    lv_obj_set_align(ui_Olho_Esq3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Olho_Esq3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Olho_Esq3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Olho_Esq3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Olho_Esq3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Olho_Dir3 = lv_obj_create(ui_OlhandoEsq);
    lv_obj_remove_style_all(ui_Olho_Dir3);
    lv_obj_set_width(ui_Olho_Dir3, 50);
    lv_obj_set_height(ui_Olho_Dir3, 50);
    lv_obj_set_x(ui_Olho_Dir3, 0);
    lv_obj_set_y(ui_Olho_Dir3, -90);
    lv_obj_set_align(ui_Olho_Dir3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Olho_Dir3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Olho_Dir3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Olho_Dir3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Olho_Dir3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Boca3 = lv_obj_create(ui_OlhandoEsq);
    lv_obj_remove_style_all(ui_Boca3);
    lv_obj_set_width(ui_Boca3, 10);
    lv_obj_set_height(ui_Boca3, 150);
    lv_obj_set_align(ui_Boca3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Boca3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Boca3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Boca3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_OlhandoEsq, ui_event_OlhandoEsq, LV_EVENT_ALL, NULL);

}
