// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Simples_screen_init(void)
{
    ui_Simples = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Simples, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Simples, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Simples, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Olho_Esq4 = lv_obj_create(ui_Simples);
    lv_obj_remove_style_all(ui_Olho_Esq4);
    lv_obj_set_width(ui_Olho_Esq4, 50);
    lv_obj_set_height(ui_Olho_Esq4, 50);
    lv_obj_set_x(ui_Olho_Esq4, 0);
    lv_obj_set_y(ui_Olho_Esq4, 90);
    lv_obj_set_align(ui_Olho_Esq4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Olho_Esq4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Olho_Esq4, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Olho_Esq4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Olho_Esq4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Olho_Dir4 = lv_obj_create(ui_Simples);
    lv_obj_remove_style_all(ui_Olho_Dir4);
    lv_obj_set_width(ui_Olho_Dir4, 50);
    lv_obj_set_height(ui_Olho_Dir4, 50);
    lv_obj_set_x(ui_Olho_Dir4, 0);
    lv_obj_set_y(ui_Olho_Dir4, -90);
    lv_obj_set_align(ui_Olho_Dir4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Olho_Dir4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Olho_Dir4, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Olho_Dir4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Olho_Dir4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Boca4 = lv_obj_create(ui_Simples);
    lv_obj_remove_style_all(ui_Boca4);
    lv_obj_set_width(ui_Boca4, 10);
    lv_obj_set_height(ui_Boca4, 150);
    lv_obj_set_align(ui_Boca4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Boca4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Boca4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Boca4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



}
